import mongoose from "mongoose";
import fs from "fs";
import path from "path";
import { config } from "../config/env";
import { ContentItem } from "../models/ContentItem";

/**
 * Seeds MongoDB with the site's full content (the single source of truth).
 *
 * Data comes from `server/content-seed.json`, generated by the frontend
 * Vite SSR exporter (`scripts/export-content.mjs`). Run that first to refresh
 * content from src/data/*.ts + the .md files.
 *
 * Usage from server/:
 *   npm run seed:content              # upsert all types (published)
 *   npm run seed:content:wipe         # also wipe the content collection first
 */

const SEED_FILE = path.resolve(__dirname, "../../content-seed.json");

type SeedRow = Record<string, unknown> & { type: string; slug: string };

async function main() {
  const mode = process.argv[2] || "seed";

  if (!fs.existsSync(SEED_FILE)) {
    console.error(
      "✖ content-seed.json not found. Run `node scripts/export-content.mjs` from the repo root first.",
    );
    process.exit(1);
  }

  const data = JSON.parse(fs.readFileSync(SEED_FILE, "utf8")) as Record<string, SeedRow[]>;
  const rows: SeedRow[] = Object.values(data).flat();

  console.log("── DevSpace Content Seed ──────────────────────────");
  console.log("  Source:", SEED_FILE);
  console.log(`  Loaded ${rows.length} content rows.`);

  try {
    await mongoose.connect(config.mongoUri);

    // Drop the deprecated global-unique slug index (if still present) so the
    // compound (type, slug) unique index is the only uniqueness constraint.
    try {
      const col = mongoose.connection.db?.collection("contentitems");
      const indexes = (await col?.indexes()) ?? [];
      const legacy = indexes.find((ix: { name?: string }) => (ix.name || "").startsWith("slug_"));
      if (legacy) {
        const fields = legacy.key as Record<string, number>;
        const onlySlug = Object.keys(fields).length === 1 && "slug" in fields;
        if (onlySlug) {
          await col?.dropIndex(legacy.name as string);
          console.log("  ✖ Dropped deprecated global slug unique index.");
        }
      }
    } catch (err) {
      console.log("  ! Could not inspect/drop legacy slug index:", (err as Error)?.message);
    }
    await ContentItem.syncIndexes().catch(() => undefined);

    if (mode === "wipe") {
      const del = await ContentItem.deleteMany({ type: { $ne: "image" } });
      console.log(`  ✖ Wiped ${del.deletedCount} content records.`);
    }

    let upserted = 0;
    const byType = new Map<string, number>();
    for (const row of rows) {
      const { type, slug } = row;
      const payload: Record<string, unknown> = { ...row, type, status: "published" };
      delete payload._id;
      await ContentItem.findOneAndUpdate(
        { type, slug },
        { $set: payload },
        { upsert: true, new: true },
      );
      upserted++;
      byType.set(type, (byType.get(type) || 0) + 1);
    }

    const total = await ContentItem.countDocuments({});
    console.log("");
    console.log("── Summary ────────────────────────────────────────");
    for (const [type, count] of [...byType.entries()].sort()) {
      console.log(`  ${type.padEnd(18)} ${count}`);
    }
    console.log("");
    console.log(`  Upserted: ${upserted}`);
    console.log(`  Total ContentItems in DB (all types): ${total}`);
  } catch (err) {
    console.error("✖ Content seed failed:", (err as Error)?.message ?? err);
    process.exit(1);
  } finally {
    await mongoose.disconnect();
  }
}

main();
